[package]
name = "trustzone-root-enclave"
# NOTE: when you update this version, please also update the psa entry in populate-test-database.sh in veracruz-server-test and veracruz-test 
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
build = "build.rs"
description = "TLS endpoint code for clients interacting with a trusted Veracruz runtime"

[[bin]]
name = "trustzone-root-enclave"
path = "src/main.rs"

[features]
default = ["tz"]
tz = []

[dependencies]
libc = { path = "../third-party/libc" }
transport-protocol = { path = "../transport-protocol", features=["tz"] }
protobuf = { path = "../third-party/protobuf/protobuf" }
psa-attestation = { path = "../psa-attestation", features=["tz"]}
# optee-utee-sys = { path="../rust-optee-trustzone-sdk/optee-utee/optee-utee-sys" }
# optee-utee = { path="../rust-optee-trustzone-sdk/optee-utee" }
veracruz-utils = { path = "../veracruz-utils", features = ["tz"] }
lazy_static = {version = "1.4.0", features=["spin_no_std"] }
ring = { path = "../third-party/ring" }
bitflags = "=1.2.1"

[build-dependencies]
uuid = { version = "=0.7.4", features = ["v4"] }

[profile.release]
lto = true
