[dependencies.std]
path = "../third-party/rust/src/libstd"

[patch.crates-io]
libc = { path = "../third-party/libc" }
compiler_builtins =  { path = "../third-party/compiler-builtins" }
rustc-std-workspace-core = { path = "../third-party/rust/src/tools/rustc-std-workspace-core" }
rustc-std-workspace-alloc = { path = "../third-party/rust/src/tools/rustc-std-workspace-alloc" }
