cargo-features = ["resolver"]

[workspace]
members = [
    "crates/proxy-attestation-server",
    "crates/veracruz-client",
    "crates/veracruz-server"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

# patches for SGX
[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path = "crates/third-party/rust-sgx-sdk/sgx_alloc", optional = true }
sgx_backtrace_sys = { path = "crates/third-party/rust-sgx-sdk/sgx_backtrace_sys", optional = true }
sgx_libc = { path = "crates/third-party/rust-sgx-sdk/sgx_libc", optional = true }
sgx_tcrypto = { path = "crates/third-party/rust-sgx-sdk/sgx_tcrypto", optional = true }
sgx_tdh = { path = "crates/third-party/rust-sgx-sdk/sgx_tdh", optional = true }
sgx_trts = { path = "crates/third-party/rust-sgx-sdk/sgx_trts", optional = true }
sgx_tstd = { path = "crates/third-party/rust-sgx-sdk/sgx_tstd", optional = true }
sgx_types = { path = "crates/third-party/rust-sgx-sdk/sgx_types", optional = true }
sgx_ucrypto = { path = "crates/third-party/rust-sgx-sdk/sgx_ucrypto", optional = true }
sgx_unwind = { path = "crates/third-party/rust-sgx-sdk/sgx_unwind", optional = true }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
serde = { git = "https://github.com/veracruz-project/serde.git", features = ["derive"], branch = "veracruz" }
