[package]
authors = ["The Veracruz Development Team"]
description = "WASM execution engine for the trusted Veracruz runtime"
edition = "2018"
name = "execution-engine"
version = "0.3.0"

[features]
default = []
icecap = [
  "platform-services/icecap",
  "policy-utils/icecap",
  "wasi-types",
]
nitro = [
  "platform-services/nitro",
  "policy-utils/std",
  "wasmtime",
]
std = [
  "platform-services/std",
  "policy-utils/std",
  "ring",
  "wasmtime",
]

[dependencies]
anyhow = { version = "1.0", default-features = false }
byteorder = "1.4.3"
cfg-if = "1"
ctor = "=0.1.16"
err-derive = "0.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
num = { version = "0.4", default-features = false }
num-derive = { version = "0.3", default-features = false }
num-traits = { version = "0.2", default-features = false }
platform-services = { path = "../platform-services" }
policy-utils = { path = "../policy-utils" }
ring = { version = "0.16.11", optional = true }
serde = { version = "1.0.115", features = ["derive"] }
typetag = "=0.1.6"
wasi-types = { git = "https://github.com/mathias-arm/wasi-types.git", branch = "veracruz" }
wasmi = { git = "https://github.com/mathias-arm/wasmi.git", branch = "workspace" }
wasmtime = { version = "0.27", optional = true }
wast = "35.0.0"

[lib]
name = "execution_engine"
path = "./src/lib.rs"
