[package]
name = "execution-engine"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "WASM execution engine for the trusted Veracruz runtime"

[features]
default = []
# NOTE: Introduce non_sgx in the dependencies to deal with sgx-related modification.
std = ["wasmi/non_sgx", "platform-services/std", "wasmtime", "ring/non_sgx", "veracruz-utils/std", "wasi-types/std"]
sgx = ["sgx_tstd", "wasmi/mesalock_sgx", "platform-services/sgx", "serde/mesalock_sgx", "typetag/mesalock_sgx", "ring/mesalock_sgx", "veracruz-utils/sgx", "wasi-types/sgx"]
# tz = ["platform-services/tz", "wasmi/non_sgx", "ring/non_sgx", "veracruz-utils/tz", "wasi-types/std"]
nitro = ["platform-services/nitro", "veracruz-utils/std", "wasmtime", "wasi-types/std"]

[dependencies]
byteorder = { path = "../third-party/byteorder" }
lazy_static = {version = "1.4.0", features = ["spin_no_std"] }
platform-services = { path = "../platform-services" }
ring = { path = "../third-party/ring" }
serde = { path = "../third-party/serde/serde", features = ["derive"] }
typetag = { path = "../third-party/typetag" }
wasmi = { path = "../third-party/wasmi" }
wasmtime = { path = "../third-party/wasmtime/crates/wasmtime", optional = true }
veracruz-utils = { path = "../veracruz-utils" }
err-derive = "0.2"
wasi-types = { path = "../third-party/wasi-types" }
pinecone = "0.2"
sgx_tstd = { path = "../third-party/rust-sgx-sdk/sgx_tstd", optional = true }
wast = "=35.0.0"
num-traits = { version = "0.2", default-features = false }
num-derive = { version = "0.3", default-features = false } 
num = { version = "0.4", default-features = false }
anyhow = { version = "1.0", default-features = false }
cfg-if = "1"

[lib]
name = "execution_engine"
path = "./src/lib.rs"

[patch.crates-io]
serde = { path = "../third-party/serde/serde", features = ["derive"] }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path = "../third-party/rust-sgx-sdk/sgx_alloc", optional = true }
sgx_tstd = { path = "../third-party/rust-sgx-sdk/sgx_tstd", optional = true }
sgx_tunittest = { path = "../third-party/rust-sgx-sdk/sgx_tunittest", optional = true }
sgx_types = { path = "../third-party/rust-sgx-sdk/sgx_types", optional = true }
sgx_urts = { path = "../third-party/rust-sgx-sdk/sgx_urts", optional = true }

