sudo: false

language: rust

cache:
    directories:
    - $HOME/.ccache

matrix:
  include:
  - rust: 1.27.2
    env: PROTOBUF_VERSION=3.5.1
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1
  - rust: beta
    env: PROTOBUF_VERSION=3.5.1
  - rust: 1.27.2
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes,with-serde
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: beta
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-serde
  - rust: nightly
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes,with-serde
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 ON_WINDOWS=1
    os: windows
  allow_failures:
  - os: windows

script:
  - ci/run.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
