[package]
authors = ["The Veracruz Development Team"]
description = "Computes the edit distance of two strings using the Rust `strsim` library."
edition = "2018"
name = "string-edit-distance"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
strsim = "0.10.0"
