[package]
name = "PSIenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "psienclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_trts = { path = "../../../../../rust-sgx-sdk/sgx_trts" }
sgx_tstd = { path = "../../../../../rust-sgx-sdk/sgx_tstd" }
sgx_tdh = { path = "../../../../../rust-sgx-sdk/sgx_tdh" }
sgx_tcrypto = { path = "../../../../../rust-sgx-sdk/sgx_tcrypto" }
sgx_tkey_exchange = { path = "../../../../../rust-sgx-sdk/sgx_tkey_exchange" }
sgx_rand = { path = "../../../../../rust-sgx-sdk/sgx_rand" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_alloc = { path = "../../../../sgx_alloc" }
sgx_backtrace = { path = "../../../../sgx_backtrace" }
sgx_backtrace_sys = { path = "../../../../sgx_backtrace_sys" }
sgx_build_helper = { path = "../../../../sgx_build_helper" }
sgx_cov = { path = "../../../../sgx_cov" }
sgx_crypto_helper = { path = "../../../../sgx_crypto_helper" }
sgx_demangle = { path = "../../../../sgx_demangle" }
sgx_libc = { path = "../../../../sgx_libc" }
sgx_rand = { path = "../../../../sgx_rand" }
sgx_rand_derive = { path = "../../../../sgx_rand_derive" }
sgx_serialize = { path = "../../../../sgx_serialize" }
sgx_serialize_derive = { path = "../../../../sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../../../sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../../../sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../../../sgx_tcrypto_helper" }
sgx_tdh = { path = "../../../../sgx_tdh" }
sgx_tkey_exchange = { path = "../../../../sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../../../sgx_tprotected_fs" }
sgx_trts = { path = "../../../../sgx_trts" }
sgx_tse = { path = "../../../../sgx_tse" }
sgx_tseal = { path = "../../../../sgx_tseal" }
sgx_tstd = { path = "../../../../sgx_tstd" }
sgx_tunittest = { path = "../../../../sgx_tunittest" }
sgx_types = { path = "../../../../sgx_types" }
#sgx_ucrypto = { path = "../../../../sgx_ucrypto" }
sgx_unwind = { path = "../../../../sgx_unwind" }
#sgx_urts = { path = "../../../../sgx_urts" }
