[package]
name = "typetag"
version = "0.1.4"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Serde serializable and deserializable trait objects"
repository = "https://github.com/dtolnay/typetag"
documentation = "https://docs.rs/typetag"
keywords = ["serde"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"
exclude = ["/sgx/*"]

#[workspace]
#members = ["impl"]

[dependencies]
erased-serde = { path = "../erased-serde" }
inventory = { path = "../inventory" }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
serde = { path = "../serde/serde", features = ["derive"] }
typetag-impl = { version = "=0.1.4", path = "impl" }
sgx_tstd = { path = "../rust-sgx-sdk/sgx_tstd", optional = true }

[dev-dependencies]
#bincode = "1.0"
#serde_json = "1.0"

[features]
default = []
mesalock_sgx = ["sgx_tstd", "erased-serde/mesalock_sgx", "inventory/mesalock_sgx",  "serde/mesalock_sgx"]
