[package]
authors = ["The Veracruz Development Team"]
description = "Image processing example. Read an image from the virtual filesystem, apply a transform to it (crop) and save it"
edition = "2018"
name = "image-processing"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
image = "0.24.0"
