[package]
authors = ["The Veracruz Development Team"]
description = "An untrusted server/bridge that allows the outside world and the trusted Veracruz runtime to communicate with each other."
edition = "2018"
name = "veracruz-server"
version = "0.3.0"

[[bin]]
name = "veracruz-server"
path = "src/cli.rs"
required-features = ["cli"]

[features]
# a feature to enable CLI-only dependencies
# https://stackoverflow.com/questions/35711044/how-can-i-specify-binary-only-dependencies
cli = [
  "actix-rt",
  "env_logger",
  "policy-utils/std",
  "structopt",
]
debug = []
icecap = [
  "bincode",
  "policy-utils/icecap",
  "psa-attestation",
  "io-utils/icecap",
  "veracruz-utils/icecap",
]
linux = [
  "bincode",
  "io-utils/linux",
  "policy-utils/std",
  "veracruz-utils/linux",
]
nitro = [
  "bincode",
  "io-utils/nitro",
  "nix",
  "policy-utils/std",
  "veracruz-utils/nitro",
]

[dependencies]
actix-http = "2.2.0"
actix-rt = { version = "1.0.0", optional = true }
actix-web = "3.3.2"
base64 = "0.10.1"
bincode = { git = "https://github.com/veracruz-project/bincode.git", branch = "veracruz", default-features = false, optional = true }
curl = "=0.4.35"
env_logger = { version = "0.7", optional = true }
err-derive = "0.2"
futures = "0.3"
hex = "0.4.2"
http = "=0.2.4"
io-utils = { path = "../io-utils", optional = true }
lazy_static = "1.4"
log = "=0.4.13"
nix = { version = "0.15", optional = true }
openssl-sys = "=0.9.70"
postcard = "0.7.2"
policy-utils = { path = "../policy-utils", optional = true }
psa-attestation = { path = "../psa-attestation", optional = true }
ring = "0.16"
rouille = "=3.2.1"
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
serde = { git = "https://github.com/veracruz-project/serde.git", branch = "veracruz", features = ["derive"] }
serde_derive = { git = "https://github.com/veracruz-project/serde.git", branch = "veracruz" }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz" }
structopt = { version = "0.3", optional = true, features = ["wrap_help"] }
tempfile = { version = "3.2.0", optional = true }
transport-protocol = { path = "../transport-protocol" }
veracruz-utils = { path = "../veracruz-utils", optional = true }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
