[package]
name = "session-manager"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "TLS endpoint and session management for the trusted Veracruz runtime"

[features]
sgx = ["veracruz-utils/sgx", "sgx_tstd", "sgx_types", "rustls/mesalock_sgx", "webpki/mesalock_sgx", "ring/mesalock_sgx", "webpki-roots/mesalock_sgx"] 
# NOTE: turn on the `std` on ring for Error trait
# tz = ["veracruz-utils/tz", "webpki/default", "webpki-roots/default", "ring/std", "ring/non_sgx", "optee-utee", "rustls/default"]
nitro = ["ring/std", "ring/non_sgx"]
std = ["veracruz-utils/std", "ring/std"]

[dependencies]
rustls = { path = "../third-party/rustls" }
ring = { path = "../third-party/ring" }
veracruz-utils = { path = "../veracruz-utils" }
webpki = { path = "../third-party/webpki" }
webpki-roots = { path = "../third-party/webpki-roots" }
err-derive = "0.2"
sgx_tstd = { path = "../third-party/rust-sgx-sdk/sgx_tstd", optional = true }
sgx_types = { path = "../third-party/rust-sgx-sdk/sgx_types", optional = true }
# optee-utee = { path = "../../rust-optee-trustzone-sdk/optee-utee", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path = "../third-party/rust-sgx-sdk/sgx_alloc", optional = true }
