[package]
authors = ["The Veracruz Development Team"]
description = "TLS endpoint and session management for the trusted Veracruz runtime"
edition = "2018"
name = "session-manager"
version = "0.3.0"

[features]
# NOTE: turn on the `std` on ring for Error trait
icecap = [
  "policy-utils/icecap",
  "ring/non_sgx",
  "ring/std",
]
nitro = [
  "policy-utils/std",
  "ring/non_sgx",
  "ring/std",
]
std = [
  "policy-utils/std",
  "ring/std",
]

[dependencies]
err-derive = "0.2"
policy-utils = { path = "../policy-utils" }
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
