cargo-features = ["resolver"]

[workspace]
resolver = "2"
members = [
    "crates/execution-engine",
    "crates/platform-services",
    "crates/psa-attestation",
    "crates/runtime-manager",
    "crates/runtime-manager-bind",
    "crates/session-manager",
    "crates/transport-protocol",
    "crates/veracruz-utils"
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

# patches for SGX
[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path = "crates/third-party/rust-sgx-sdk/sgx_alloc", optional = true }
sgx_libc = { path = "crates/third-party/rust-sgx-sdk/sgx_libc", optional = true }
sgx_tcrypto = { path = "crates/third-party/rust-sgx-sdk/sgx_tcrypto", optional = true }
sgx_tdh = { path = "crates/third-party/rust-sgx-sdk/sgx_tdh", optional = true }
sgx_trts = { path = "crates/third-party/rust-sgx-sdk/sgx_trts", optional = true }
sgx_tstd = { path = "crates/third-party/rust-sgx-sdk/sgx_tstd", optional = true }
sgx_types = { path = "crates/third-party/rust-sgx-sdk/sgx_types", optional = true }
sgx_ucrypto = { path = "crates/third-party/rust-sgx-sdk/sgx_ucrypto", optional = true }

[patch.crates-io]
serde = { path = "crates/third-party/serde/serde", features=["derive"] }
rustls = { path = "crates/third-party/rustls" }
