# workspaces/nitro-runtime/Cargo.toml:
# Workspace for trusted Nitro services
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root director for licensing
# and copyright information.

cargo-features = ["resolver"]

[workspace]
members = [
  "crates/runtime-manager",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[patch.crates-io]
ring = { git = "https://github.com/mathias-arm/ring.git", branch = "nitro" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
webpki = { git = "https://github.com/mathias-arm/webpki.git", branch = "unrecognized_extensions" }
