cargo-features = ["resolver"]

[workspace]
members = [
  "crates/execution-engine",
  "crates/platform-services",
  "crates/psa-attestation",
  "crates/runtime-manager",
  "crates/session-manager",
  "crates/transport-protocol",
  "crates/veracruz-utils",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[patch.crates-io]
ring = { git = "https://github.com/mathias-arm/ring.git", branch = "nitro" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
serde = { git = "https://github.com/veracruz-project/serde.git", branch = "veracruz", features = ["derive"] }
webpki = { git = "https://github.com/mathias-arm/webpki.git", branch = "unrecognized_extensions" }

