[package]
authors = ["The Veracruz Development Team"]
description = "A test program for calling the TensorFlow Lite inference module on a MNIST model."
name = "tflite-inference-native-mnist"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
image = "0.24.4"
libc = "0.2.137"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", features = ["derive"] }
