[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
bincode = { path = "../../.." }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx.git" }
#serde_bytes = { git = "https://github.com/mesalock-linux/serde-bytes-sgx".git }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" }
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx.git" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_tstd = { path = "../../../../../rust-sgx-sdk/sgx_tstd" }
sgx_tunittest = { path = "../../../../../rust-sgx-sdk/sgx_tunittest" }
