[package]
authors = ["The Veracruz Development Team"]
description = "Computes the sum of values associated with keys k_i in set A where keys k_i also appear in set B."
edition = "2018"
name = "intersection-set-sum"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", default-features = false, features = ["derive"] }
