[package]
authors = ["The Veracruz Development Team"]
description = "The test program for calling the AES counter mode native module."
name = "aesctr-native"
version = "0.3.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", features = ["derive"] }
