[package]
name = "veracruz-utils"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"

[features]

sgx = ["sgx_tstd", "serde/mesalock_sgx", "serde_json/mesalock_sgx", "serde_json/alloc", "ring/mesalock_sgx", "wasi-types/sgx"]
# tz = ["serde_json/std", "ring/non_sgx", "wasi-types/std"]
std = ["x509-parser", "serde/std", "rustls","serde_json/std", "actix-web", "futures", "actix-http", "failure", "ring", "wasi-types/std"]
nitro = ["serde_json/std", "nix", "byteorder", "ring/non_sgx", "wasi-types/std"]
linux = ["serde_json/std", "nix", "byteorder", "ring/non_sgx", "wasi-types/std"]

[dependencies]
sgx_tstd = { path = "../third-party/rust-sgx-sdk/sgx_tstd", optional = true }
serde = { path = "../third-party/serde/serde", features = ["derive"] }
x509-parser = { version = "0.7.0", optional = true }
serde_json = { path = "../third-party/serde_json", default-features = false }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = { path = "../third-party/rustls", optional = true }
actix-web = { version = "3.3.2", optional = true }
futures = { version = "0.3", optional = true }
actix-http = { version = "2.2.0", optional = true }
failure = { version = "0.1", optional = true }
err-derive = "0.2"
nix = { version = "0.15", optional = true }
byteorder = { version = "1.3", optional = true }
hex = { version = "=0.4.2", default-features = false }
ring = { path = "../third-party/ring", optional = true }
wasi-types = { path = "../third-party/wasi-types" }
http = "=0.2.4"

[build-dependencies]
uuid = { version = "0.7", features = ["v4"] }

[patch.crates-io]
ring = { path = "../third-party/ring", optional = true }
rustls = { path = "../third-party/rustls", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path = "../third-party/rust-sgx-sdk/sgx_alloc", optional = true }
