[package]
authors = ["The Veracruz Development Team"]
description = "Veracruz integration test-suite.  Tests trusted Veracruz runtime functioanlity, and session management code, without establishing a network connection."
edition = "2018"
name = "veracruz-server-test"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# debug feature means the enclaves will be started in debug mode (when available)
# which changes behaviors depending on the platform (for example in Debug mode,
# Nitro enclave attestation documents have the PCRs zeroed out and the console
# cannot connect)
debug = ["veracruz-server/debug"]
icecap = [
  "policy-utils/icecap",
  "proxy-attestation-server/icecap",
  "veracruz-server/icecap",
  "veracruz-utils/icecap",
]
icecap-lkvm = ["veracruz-server/icecap-lkvm"]
icecap-qemu = ["veracruz-server/icecap-qemu"]
linux = [
  "policy-utils/std",
  "proxy-attestation-server/linux",
  "veracruz-server/linux",
  "veracruz-utils/linux",
]
nitro = [
  "policy-utils/std",
  "proxy-attestation-server/nitro",
  "veracruz-server/nitro",
  "veracruz-utils/nitro",
]

[dependencies]
actix-rt = "2"
curl = "0.4.43"
either = "1.6.1"
env_logger = "0.9.0"
hex = "0.4.2"
lazy_static = "1.4"
log = "0.4.13"
policy-utils = { path = "../policy-utils", optional = true }
proxy-attestation-server = { path = "../proxy-attestation-server" }
rustls = "0.20.4"
rustls-pemfile = "0.3.0"
transport-protocol = { path = "../transport-protocol" }
veracruz-server = { path = "../veracruz-server" }
veracruz-utils = { path = "../veracruz-utils", optional = true }
webpki = "0.22"
webpki-roots = "0.22"
