[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic strings for use with various examples (e.g. `string-edit-distance`)."
edition = "2018"
name = "string-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
