[package]
authors = ["The Veracruz Development Team"]
description = "Computes the moving-average-convergence-divergence (MACD) metric of a dataset.  This is often used in financial mathematics."
edition = "2018"
name = "moving-average-convergence-divergence"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
