[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating secrets for Veracruz's Shamir secret sharing example."
edition = "2018"
name = "shamir-secret-sharing-generator"
version = "0.3.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
hex = "0.4"
rand = "0.8.3"
