[package]
authors = ["The Veracruz Development Team"]
description = "A Rust reimplementation of the winning logistic regression entry in the IDASH 2017 competition."
edition = "2018"
name = "idash2017-logistic-regression"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
