[package]
authors = ["The Veracruz Development Team"]
description = "Samples random data from the trusted Veracruz runtime.  Used to test random number generation in Veracruz."
edition = "2018"
name = "random-source"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
rand = "0.8.3"
