[package]
name = "app"
version = "1.0.0"
authors = ["The Teaclave Authors"]
build = "build.rs"

[dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../../../../rust-sgx-sdk/sgx_urts" }
itertools = "*"

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_types = { path = "../../../../sgx_types" }
sgx_urts = { path = "../../../../sgx_urts" }
