[package]
authors = ["The Veracruz Development Team"]
description = "Another pure-Rust implementation of logistic regression."
edition = "2018"
name = "linear-regression"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", default-features = false, features = ["derive"] }
