[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
erased-serde = { path = "../../.." }
serde_cbor = { git = "https://github.com/mesalock-linux/cbor-sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_tstd = { path = "../../../../../rust-sgx-sdk/sgx_tstd" }
sgx_tunittest = { path = "../../../../../rust-sgx-sdk/sgx_tunittest" }
