[package]
name = "runtime_manager_enclave"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
build = "build.rs"
description = "The trusted Veracruz runtime's command-and-control module.  Co-ordinates and directs the rest of the runtime."

[lib]
name = "runtime_manager_enclave"
crate-type = ["staticlib"]
path = "src/lib.rs"

[[bin]]
name = "runtime_manager_enclave"
path = "src/main.rs"

[features]
sgx = ["transport-protocol/sgx", "session-manager/sgx", "veracruz-utils/sgx", "wasmi/mesalock_sgx", "execution-engine/sgx", "rustls/mesalock_sgx", "protobuf/mesalock_sgx", "ring/mesalock_sgx", "sgx_types" , "sgx_tstd", "sgx_tcrypto", "sgx_tdh", "wasi-types/sgx"]
# tz = ["wasmi/std", "session-manager/tz", "execution-engine/tz", "veracruz-utils/tz", "libc", "optee-utee-sys", "optee-utee", "serde_json/alloc", "wasi-types/std"]
nitro = ["execution-engine/nitro", "wasmi/non_sgx", "session-manager/nitro", "veracruz-utils/nitro", "nsm_io", "nsm_lib", "ring/nitro", "nix", "byteorder", "bincode", "wasi-types/std"]
linux = ["execution-engine/std", "wasmi/non_sgx", "session-manager/std", "veracruz-utils/linux", "byteorder", "clap", "nix", "bincode", "wasi-types/std"]

[dependencies]
clap = {version = "2.33", optional = true}
log = "0.4.14"
env_logger = "0.8.3"
session-manager = { path = "../session-manager"}
lazy_static = {version = "1.4.0", features=["spin_no_std"] }
execution-engine = { path = "../execution-engine" }
transport-protocol = { path = "../transport-protocol" }
protobuf = { path = "../third-party/protobuf/protobuf" }
rustls = { path = "../third-party/rustls" }
ring = { path = "../third-party/ring" }

veracruz-utils = { path = "../veracruz-utils" }
wasmi = { path = "../third-party/wasmi" }
hex = { version = "=0.4.2", default-features = false }
serde_json = { path = "../third-party/serde_json" }
err-derive = "0.2"
nix = { version = "0.15", optional = true}
byteorder = { version = "1.3", optional = true }
bincode = { path = "../third-party/bincode", default-features = false, optional = true }
libc = { path = "../third-party/libc", optional = true }
# optee-utee-sys = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz", optional = true }
# optee-utee = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz", optional = true }
nsm_lib = { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git/", branch = "main", package="nsm-lib", optional = true }
nsm_io =  { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git/", branch = "main", package = "nsm-io", optional = true }
sgx_alloc = { path = "../third-party/rust-sgx-sdk/sgx_alloc", optional = true }
sgx_tcrypto = { path = "../third-party/rust-sgx-sdk/sgx_tcrypto", optional = true }
sgx_tdh = { path = "../third-party/rust-sgx-sdk/sgx_tdh", optional = true }
sgx_tstd = { path = "../third-party/rust-sgx-sdk/sgx_tstd", optional = true }
sgx_types = { path = "../third-party/rust-sgx-sdk/sgx_types", optional = true }
bitflags = "=1.2.1"
wasi-types = { path = "../third-party/wasi-types" }

[patch.crates-io]
atty = { git = "https://github.com/veracruz-project/atty", version = "0.2" }

[build-dependencies]
uuid = { version = "0.7", features = ["v4"] }

[profile.release]
lto = true
