[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous code related to the Veracruz policy."
edition = "2018"
name = "policy-utils"
version = "0.3.0"

[features]
icecap = []
std = [
  "hex/std",
  "rustls",
  "serde/std",
  "serde_json/std",
  "x509-parser",
]

[dependencies]
err-derive = { version = "0.2", default-features = false }
hex = { version = "0.4.2" }
lexical-core = { version = "0.8.2", default-features = false }
ring = "0.16.11"
rustls = { version = "0.16", optional = true }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }
x509-parser = { version = "0.12.0", optional = true }
