[package]
name = "app"
version = "1.0.0"
authors = ["The Teaclave Authors"]
edition = '2018'

[dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_urts = { path = "../../../../../rust-sgx-sdk/sgx_urts" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_types = { path = "../../../sgx_types" }
sgx_urts = { path = "../../../sgx_urts" }
