[package]
name = "transport-protocol"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Veracruz protocol message wire-format parsing and serialization code for the trusted Veracruz runtime"
build = "build.rs"

[features]
sgx = ["protobuf/mesalock_sgx", "sgx_types", "sgx_tstd"]
sgx_attestation = ["sgx_types"]
# tz = []

[dependencies]
protobuf = { path = "../third-party/protobuf/protobuf" }
err-derive = "0.2"
sgx_types = { path="../third-party/rust-sgx-sdk/sgx_types", optional = true }
sgx_tstd = { path="../third-party/rust-sgx-sdk/sgx_tstd", optional = true }

[build-dependencies]
protoc-rust = { path = "../third-party/protobuf/protoc-rust" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { path="../third-party/rust-sgx-sdk/sgx_alloc", optional = true }
