[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
indexmap = { path = "../../..", features = ["serde-1"] }
serde_test = { git = "https://github.com/mesalock-linux/serde-sgx" }
fnv = { git = "https://github.com/mesalock-linux/rust-fnv-sgx" }
itertools = { version = "*", default-features = false }


[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../../../rust-sgx-sdk/sgx_types" }
sgx_tstd = { path = "../../../../../rust-sgx-sdk/sgx_tstd" }
sgx_tunittest = { path = "../../../../../rust-sgx-sdk/sgx_tunittest" }
