[package]
authors = ["The Veracruz Development Team"]
description = "Computes the sum of values associated with keys k_i appearing in set A where k_i also appears in set B."
edition = "2018"
name = "private-set-intersection-sum"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
