name: Veracruz-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  icecap:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/veracruz-project/veracruz/ci:v22.05
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Running IceCap test script
        id: icecap-build
        run: |
            make -C /work/veracruz/workspaces/icecap-runtime build PROFILE=dev
            make -C /work/veracruz/workspaces/icecap-host test-client veracruz-test PROFILE=dev
